
- name: create directory for virtualenvs
  command: mkdir /home/{{username}}/Envs creates=/home/{{username}}/Envs

- name: create virtualenvs for all projects I'm working on
  command: virtualenv --no-site-packages {{item}} 
           chdir=/home/{{username}}/Envs
  with_items:
    - metareact
    - plushcap
    - pcf
