
- name: ensure apt cache is up to date
  apt:  update_cache=yes
  sudo: yes

- name: ensure development system packages are installed
  apt:  name={{item}}
  sudo: yes
  with_items:
    - git
    - python-dev
    - python-virtualenv
    - libpq-dev
    - postgresql
    - postgresql-client
    - postgresql-client
    - vim

- name: write .vimrc configuration
  template: src=vimrc.j2 dest=/home/{{username}}/.vimrc

- name: write .bashrc configuration
  template: src=bashrc.j2 dest=/home/{{username}}/.bashrc

- include: create_virtualenvs.yml

- name: create directory for development
  command: mkdir -p /home/{{username}}/devel/py 
           creates=/home/{{username}}/devel/py

- name: pull all projects from remote Git repos
  git: repo={{item}} dest=/home/{{username}}/devel/py/{{item}}
       accept_hostkey=true
       key_file=/home/{{username}}/.ssh/github
  with_items:
    - git@github.com:makaimc/plushcap.git
    - git@github.com:makaimc/plushcap-flask.git
    - git@github.com:makaimc/metareact.git
